name: ML Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  AWS_BUCKET_NAME: c2k
  AWS_ROLE: ${{ secrets.AWS_ROLE }}

jobs:
  train_and_upload:
    name: Train and Upload
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: GithubActionsC2KSession
          aws-region: ${{ env.AWS_REGION }}

      - name: Train and Upload to S3
        run: |
          pip install -r requirements.txt
          python ci_train_and_upload.py
